name: stable

on:
  push:
    branches:
      - mc*/release

jobs:
  publish:
    concurrency:
      group: stable
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Extract Version
        run: |
          echo "VERSION=$(./gradlew properties --console=plain | grep 'version:'  | sed 's/version:\s*//g')" >> $GITHUB_ENV
          echo "MINECRAFT_VERSION=$(grep minecraftVersion= gradle.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          prerelease: false
          body: ${{ github.event.head_commit.message }}
          files: |
            ./build/libs/*-all.jar

      - name: Modrinth Release
        uses: benwoo1110/modrinth-upload-action@main
        with:
          api_token: ${{ secrets.MODRINTH_TOKEN }}
          project_id: puTJzCb0
          version_number: ${{ env.VERSION }}
          files: '["${{ github.workspace }}/build/libs/lavafishing-${{env.VERSION}}-all.jar"]'
          game_versions: ${{ env.MINECRAFT_VERSION }}

